<?php
use Flywheel\View\Render;

/** @var Render $this */

$document = $this->document();



$document->addJs('js/libs/jquery-1.12.3.min.js', 'TOP');
$document->addJs('js/libs/angular.min.js', "TOP");

var_dump($document);

?>

<script>
    angular.module('MyForm', [])
        .controller('ExampleController', ['$scope', function($scope) {
        }]);
</script>
<style>
    .my-input {
        -webkit-transition:all linear 0.5s;
        transition:all linear 0.5s;
        background: transparent;
    }
    .my-input.ng-invalid {
        color:white;
        background: red;
    }
</style>

<div ng-app="MyForm">
    <form name="testForm" ng-controller="ExampleController">
        <input ng-model="val" ng-pattern="/^\d+$/" name="anim" class="my-input" />
    </form>
</div>
